# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prevett < Formula
  desc "CLI for pre-submission validation of iOS and Android apps"
  homepage "https://github.com/prevettdev/prevett"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.9/prevett-0.1.9-darwin-amd64.tar.gz"
      sha256 "59d0c8c5a493e63ad478de516dab664d92fdc978c7ce6b41118448553ba53713"

      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.9/prevett-0.1.9-darwin-arm64.tar.gz"
      sha256 "7e53007bfc461ba713de568c9c479565f29693ee3035aad778e9e2b5781daca0"

      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.9/prevett-0.1.9-linux-amd64.tar.gz"
      sha256 "e63831bee428f1c5fcebf97f758723cab3928186861bd37c52664d5c181fa2ab"
      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.9/prevett-0.1.9-linux-arm64.tar.gz"
      sha256 "8716c9c30f1b6d0dd31c90c49e3922022133d41a84a1914920885eaca7e264ca"
      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
  end

  test do
    system "#{bin}/prevett", "version"
  end
end
