# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prevett < Formula
  desc "CLI for pre-submission validation of iOS and Android apps"
  homepage "https://github.com/prevettdev/prevett"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.6/prevett-0.1.6-darwin-amd64.tar.gz"
      sha256 "ccb6d1e0973c8e18c19d91a75c9010160f76cfe06615978cf4f7fa470f6475e3"

      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.6/prevett-0.1.6-darwin-arm64.tar.gz"
      sha256 "0f0bc189bf1f6a8feb40879f4f53eb967c61d6351c9848cbc83527ea663f23be"

      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.6/prevett-0.1.6-linux-amd64.tar.gz"
      sha256 "a3d673a1205cbdd3697b62075c2402b1858ecb9454473162fb530c76f0d88ba3"
      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.6/prevett-0.1.6-linux-arm64.tar.gz"
      sha256 "59193abe03b2c0c18c9d43d15728e1ad0694509e63e8c8e9f4731b1ab68c7091"
      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
  end

  test do
    system "#{bin}/prevett", "version"
  end
end
