# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prevett < Formula
  desc "CLI for pre-submission validation of iOS and Android apps"
  homepage "https://github.com/prevettdev/prevett"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.7/prevett-0.1.7-darwin-amd64.tar.gz"
      sha256 "756629410900d29564745e2f532528418e45208e640b715cdc872781d44f9511"

      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.7/prevett-0.1.7-darwin-arm64.tar.gz"
      sha256 "f767da885dec0fc4605d70b607b15dc7fdd35e15dbb720582c6f4df7a2fcc08d"

      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.7/prevett-0.1.7-linux-amd64.tar.gz"
      sha256 "689965a383db812b3893970267c675a59c38b4987ae0728e1ac100259a9301e5"
      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prevettdev/homebrew-tap/releases/download/v0.1.7/prevett-0.1.7-linux-arm64.tar.gz"
      sha256 "fc6160630d2d7e90b6a000ad09df28613a8b1b000a88456b600fb48eac7c4fc7"
      define_method(:install) do
        bin.install "prevett"
        system "#{bin}/prevett", "install"
      end
    end
  end

  test do
    system "#{bin}/prevett", "version"
  end
end
